import 'dart:ui' as ui;

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'src/api/api_client.dart';
import 'src/api/token_provider.dart';
import 'src/app.dart';
import 'src/auth/auth_service.dart';
import 'src/auth/biometric_gate.dart';
import 'src/render/sprite_sheet.dart';
import 'src/state/app_controller.dart';

/// Server address, overridable at build time:
///
///   flutter run --dart-define=API_BASE_URL=http://10.0.2.2:8080
///
/// 10.0.2.2 is the host loopback as seen from the Android emulator; localhost
/// inside the emulator is the emulator itself.
const apiBaseUrl = String.fromEnvironment(
  'API_BASE_URL',
  defaultValue: 'http://localhost:8080',
);

/// A Firebase ID token for local development, used only when Firebase itself
/// is not configured:
///
///   flutter run --dart-define=DEV_ID_TOKEN=<token>
const devIdToken = String.fromEnvironment('DEV_ID_TOKEN', defaultValue: '');

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase needs google-services.json / GoogleService-Info.plist, which are
  // generated by `flutterfire configure` and are not in the repo. Rather than
  // crashing on a fresh clone, fall back to the dev token path and say so.
  var firebaseReady = false;
  try {
    await Firebase.initializeApp();
    firebaseReady = true;
  } on FirebaseException catch (e) {
    debugPrint('Firebase is not configured (${e.code}); '
        'falling back to the dev token. Run `flutterfire configure` to enable sign-in.');
  } catch (e) {
    debugPrint('Firebase failed to initialise: $e');
  }

  final TokenProvider tokens;
  MfaEnroller? enroller;
  SignInGateway? gateway;

  if (firebaseReady) {
    final auth = AuthService();
    tokens = FirebaseTokenProvider(auth.raw);
    enroller = auth;
    gateway = auth;
  } else {
    tokens = devIdToken.isEmpty
        ? const NoTokenProvider()
        : StaticTokenProvider(devIdToken);
  }

  final api = ApiClient(baseUrl: apiBaseUrl, tokens: tokens);

  runApp(XPGainApp(
    controller: AppController(api: api, tokens: tokens),
    loadAtlas: loadPlaceholderAtlas,
    enroller: enroller,
    gateway: gateway,
    // Optional by default: a phone with no enrolled biometric must still work.
    biometricGate: BiometricGate(authenticator: LocalAuthenticator()),
  ));
}

/// Dev-only: synthesises sprite sheets so the renderer runs before any art
/// exists. Replace with `SpriteAtlas.load({...})` once real sheets land in
/// assets/sprites/.
Future<SpriteAtlas> loadPlaceholderAtlas() async {
  const palette = <String, Color>{
    'body_base': Color(0xFF8D6E63),
    'legs_cloth': Color(0xFF455A64),
    'torso_plate': Color(0xFF90A4AE),
    'helm_iron': Color(0xFFCFD8DC),
    'sword_steel': Color(0xFFFFD54F),
  };

  const frameW = 64, frameH = 64, cols = 8, rows = 4;
  final images = <String, ui.Image>{};

  for (final entry in palette.entries) {
    final recorder = ui.PictureRecorder();
    final canvas = Canvas(recorder);
    final paint = Paint()..color = entry.value;

    for (var row = 0; row < rows; row++) {
      for (var col = 0; col < cols; col++) {
        final bob = (col % 4) - 1.5;
        canvas.drawRect(
          Rect.fromLTWH(col * frameW + 20.0, row * frameH + 16.0 + bob * 2, 24, 36),
          paint,
        );
      }
    }
    final picture = recorder.endRecording();
    images[entry.key] = await picture.toImage(frameW * cols, frameH * rows);
    picture.dispose();
  }

  return SpriteAtlas.fromImages(images,
      frameWidth: frameW, frameHeight: frameH, columns: cols);
}
